#!/usr/bin/env bash



THEME='Dracula'
ICONS='Zafiro-Purple'
FONT='Noto Sans 9'
CURSOR='Future'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
